version: '3.4'

services:
  troupon-sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  troupon-checkout-api:
    image: troupon.checkout.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Troupon.checkout.Api/Dockerfile
    depends_on:
      - troupon-sqldata
